### ISSUE TITLE
Trigger Event Only Fire Once

### ISSUE THREAD

**Issue by alpezed** [Theme-Fusion/Fusion-Builder-Sample-Add-On#38] opened 2019-08-18 14:11 UTC
Hi, I have read the documentation here about JS event for render update https://github.com/Theme-Fusion/Fusion-Builder-Sample-Add-On/tree/front-end#js-events-for-render-update, but the event is only trigger once and it is only trigger when i added the element, I have no underscore template for my shortcodes and it is only a server side render, i am not sure how to achieve this using only a shortcode and no js template because i have a lot of shortcodes and i don't need to create a templae for each shortcode. Can you please help about this issue. Thank you

**Comment by mikka23** [comment] 2019-08-19 08:56
Hi @alpezed 

The event really should be triggered after every change as well, but right now I see that it isn't.  I will check into adding that for option change as well.  

Other than that, you can have a custom JS view without the need for a template.  You can then use the afterPatch method to fire some JS that you like.  You can enqueue that on the builder frame using the hook `fusion_builder_admin_scripts_hook`.  In that you can add your custom JS.  For example:

```js
var FusionPageBuilder = FusionPageBuilder || {};
( function() {

	jQuery( document ).ready( function() {

		// My Shortcode
		FusionPageBuilder.my_shortcode = FusionPageBuilder.ElementView.extend( {

			afterPatch: function() {
				// This will trigger a JS event on the preview frame
				this._refreshJs();

				// Alternatively target it from here.
				this.$el.doSomething();
			}
		} );
	} );
}( jQuery ) );
```

If you wanted them to be the same for lots of shortcodes you could do something like:
```js
var FusionPageBuilder = FusionPageBuilder || {};
( function() {

	jQuery( document ).ready( function() {

		var myShortcodes = [ 'myshortcode_1', 'myshortcode_2' ],
                      mySharedView = FusionPageBuilder.ElementView.extend( {

			afterPatch: function() {
				// This will trigger a JS event on the preview frame
				this._refreshJs();

				// Alternatively target it from here.
				this.$el.doSomething();
			}
		} );

		_.each( myShortcodes, function( shortcode ) {
			FusionPageBuilder[ shortcode ] = mySharedView;
		} );
	} );
}( jQuery ) );
```

**Comment by alpezed** [comment] 2019-08-19 15:25
Hi @mikka23 Thanks for your answer and It seems like that scripts are working and trigger after every change but the problem is i don't want to duplicate my script inside the **FusionPageBuilder.ElementView.extend** because those scripts are used on the other builders example i have a function script called `function betterPostGridInit() {...}` and this scripts is handle my grid, posts and masonry shortcode for all the builders but because this is outside the **FusionPageBuilder.ElementView.extend** it is not available inside the **afterPatch** and it is undefined and i don't want to duplicate this function because there are lot of functions scripts connected on `function betterPostGridInit() {...}` and it will heavy if i duplicate all the script inside **FusionPageBuilder.ElementView.extend**, I hope there are some other way but if no i will wait the next update for this. Thanks

**Comment by mikka23** [comment] 2019-08-19 15:41
Hi,

The function will still be there, just the issue is that there are two frames.  So if you add an extended view that is within the builder frame, with the regular preview code on the preview frame. If you check the previewframe window you should see the function that you can call

Eg
```js
jQuery( '#fb-preview' )[ 0 ].contentWindow.betterPostGridInit();
```

Alternatively you can just use the JS trigger which the `this._refreshJs();` calls.  (It calls the same trigger as initial render)

**Comment by alpezed** [comment] 2019-08-19 15:58
Hi, I tried to do that but i have an error on my console **Uncaught TypeError: jQuery(...)[0].contentWindow.betterPostGridInit is not a function**

and here's my scripts below:

```
var FusionPageBuilder = FusionPageBuilder || {};
(
	function( $ ) { 
		'use strict';

		...

		jQuery( document ).ready( function( $ ) {
			'use strict';
		
			...
		
			betterPostGridInit();

            ...
		
			function betterPostGridInit() {
				...
			}
		
			/**
			 * Calculate size for grid classic + masonry.
			 */
			function betterGridMasonryCalculateSize( $el, $grid, $isotopeOptions ) {
				...
			}
		
			/**
			 * Load post infinity from db.
			 */
			function betterAjaxPostQuery( $wrapper, $grid, reset ) {
				...
			}
		
			/**
			 * Remove pagination if has no posts anymore
			 *
			 * @param $el
			 * @param query
			 *
			 */
			function betterHidePaginationIfEnd( $el, query ) {
				...
			}
		
			function betterGridFilterHandler( $el, $grid ) {
				...
			}
			
			function betterInitGridAnimation( $grid, $items ) {
				...
			}
		
			handlerTestimonials();
		
			function handlerTestimonials() {
				...
			}
		
			handlerSliderModern();
		
			function handlerSliderModern() {
				...
			}

			// Better Shortcodes
			FusionPageBuilder.better_posts = FusionPageBuilder.ElementView.extend( {

				afterPatch: function() {
					// This will trigger a JS event on the preview frame
					this._refreshJs();

					// Alternatively target it from here.
					// this.$el.doSomething();

					jQuery( '#fb-preview' )[ 0 ].contentWindow.betterPostGridInit();
				},

			} );
		
		});

		function processItemQueue( itemQueue, queueDelay, queueTimer, queueResetDelay ) {
			...
		}

		$.fn.betterSwiper = function() { 
            ...
		};

	}( jQuery )
);
```

**Comment by alpezed** [comment] 2019-08-19 16:05
I noticed this hook `fusion_builder_admin_scripts_hook` is not working on front end builder.

**Comment by mikka23** [comment] 2019-08-19 16:08
Hi alpezed,

It really depends on what you are adding.  The code I referenced was for JS you already have loaded in the preview frame. If you were to declare in the builder frame then the reference would be incorrect.

In order to help it would probably be best for you to explain the specific setup you currently have with the shortcode and what you are trying to achieve (just use a single shortcode of yours as an example).  Also if you have code already for it please let me know (include a zip of the plugin if it is a plugin eg)

**Comment by alpezed** [comment] 2019-08-19 16:24
I am doing it in the live editor or front end builder of the new version of avada 6.0.

**Comment by mikka23** [comment] 2019-08-19 16:27
Hi, 

I could really do with a single example of the problem you face.  Can you show me a specific coding example of a shortcode that you have right now that you want to work in the live editor?  That was I can recommend best approach with least extra coding.

**Comment by alpezed** [comment] 2019-08-20 01:52
Hi @mikka23 , I was able to figure our the problem after a lot of debugging, and this solution `jQuery( '#fb-preview' )[ 0 ].contentWindow.betterPostGridInit();` is working after i moved the functions scripts `betterPostGridInit()` and the other functions outside the 

```
(
	function( $ ) { 
		'use strict';

		jQuery( document ).ready( function( $ ) { ... });
        
    }( jQuery )
);
```

Is there any other way to access the function scripts inside the 
```
(
	function( $ ) { 
		'use strict';

		jQuery( document ).ready( function( $ ) { ... });
        
    }( jQuery )
);
``` 
? Thank you for helping.

**Comment by maximus80** [comment] 2019-08-20 04:16
Glad to hear it works now for you :+1:
Closing this one out.

**Closed as completed by maximus80** 2019-08-20 04:16 UTC
Labels: help wanted

**Comment by alpezed** [comment] 2019-08-20 04:46
I still have a concern, if is there any other way to access the function scripts inside the code below
```
(
	function( $ ) { 
		'use strict';

		jQuery( document ).ready( function( $ ) { ... });
        
    }( jQuery )
);
```
?

Because for now it only works after i moved the scripts outside that code, but still i need to wrap the functions script inside that code above.

**Comment by mikka23** [comment] 2019-08-20 08:38
Hi alpezed, that code should work already.  Just as an example, this works fine for me:
```js
var FusionPageBuilder = FusionPageBuilder || {};
(
	function( $ ) {
		'use strict';

		jQuery( document ).ready( function( $ ) {
			'use strict';


			function betterPostGridInit() {
				console.log( 'Firing' );
			}

			// Better Shortcodes
			FusionPageBuilder.better_posts = FusionPageBuilder.ElementView.extend( {

				afterPatch: function() {

					betterPostGridInit();
				},

			} );

		});

	}( jQuery )
);
```

**Comment by alpezed** [comment] 2019-08-20 11:59
Hi mikka23, I always got an error using that code here's the error on console

![2019-08-20_1957](https://user-images.githubusercontent.com/4197193/63345260-ebc27580-c384-11e9-8564-b7cc56010e5e.png)

Also how did you enqueue the scripts? I'm just using the 'wp_enqueue_scripts' action

**Comment by mikka23** [comment] 2019-08-20 12:14
That looks like it is running on the preview frame.  It needs to be on the builder frame which is where the actual editor part is.

So it would be like this in a child theme:
```php
function add_my_scripts() {
    wp_enqueue_script( 'my_builder_override', get_stylesheet_directory_uri() . '/my-overrides.js', [], 1, true );
}
add_action( 'fusion_builder_enqueue_live_scripts', 'add_my_scripts' );
```

Just tested that and working correctly for me.

**Comment by alpezed** [comment] 2019-08-20 12:28
Okay, sorry but i forgot to tell you that i separated this scripts below in the other file.

```
fusion.js
var FusionPageBuilder = FusionPageBuilder || {};

( function() {

	jQuery( document ).ready( function() {

		// Better Shortcodes
		var bettershortcodes = [ 'better_posts', 'better_testimonial', 'better_clients' ];
			bettershortcodesView = FusionPageBuilder.ElementView.extend( {

			afterPatch: function() {
				// This will trigger a JS event on the preview frame
				this._refreshJs();

				// Alternatively target it from here.
				jQuery( '#fb-preview' )[ 0 ].contentWindow.betterPostGridInit();
			},

		} );

		_.each( bettershortcodes, function( shortcode ) {
			FusionPageBuilder[ shortcode ] = bettershortcodesView;
		} );

    } );
}( jQuery ) );
```

and i just want to call the function `betterPostGridInit` from other file but inside the

```
frontend.js
(
	function( $ ) { 
		'use strict';

		jQuery( document ).ready( function( $ ) { ... });
        
    }( jQuery )
);
```

**Comment by mikka23** [comment] 2019-08-20 12:32
Hi,

The first example you have should be on hook `fusion_builder_enqueue_live_scripts`.  That is the builder frame code.


Now for betterPostGridInit, does this function already exist?  If so where and what exactly is the second file in your example for?  If betterPostGridInit is something you use on regular page load then it already exists in preview frame and you shouldn't need to add anything else.  Just that first file should do everything.

**Comment by alpezed** [comment] 2019-08-20 14:08
the betterPostGridInit is in the frontend.js file and i want to access that function to fusion.js using jQuery( '#fb-preview' )[ 0 ].contentWindow.betterPostGridInit(); but it didn't work because when i tried to run `jQuery( '#fb-preview' )[ 0 ].contentWindow` in the console the betterPostGridInit is not found and i think because the function is wrap inside the document ready but if i moved the betterPostGridInit  outside the document ready then i was able to access using `jQuery( '#fb-preview' )[ 0 ].contentWindow.betterPostGridInit();`

**Comment by mikka23** [comment] 2019-08-20 14:28
If the function is within frontend.js and that file is enqueued in the preview frame (not builder) then it will be available.  But you need to ensure the timing is correct.  If you are calling that function on option change/element add then timing will be fine.

If you are checking in the console, ensure you are adding it into the console for the top level frame.  

But this sounds a bit strange and like you might be adding more code that necessary.  On a regular page load what JS do you run for your shortcodes?  Because whatever that JS is, you can just use that, and it will already be there.
